# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 06:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"result":"Not Yet"}'),
        ),
    ]
