# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict_app', '0003_auto_20171105_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(null=True, upload_to='sheets/%Y/%m/%d')),
                ('weather', models.CharField(choices=[('Use', 'Using weather data'), ('Not', 'Not using weather data')], max_length=5)),
                ('timestep', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PalletData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=30, null=True)),
                ('pallet_out', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_app.FileUploadHistory')),
            ],
        ),
        migrations.CreateModel(
            name='TotalPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_pallet_out', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filetask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='total_prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='predict_app.TotalPrediction'),
        ),
    ]
