# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict_app', '0005_auto_20171106_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletdata',
            name='pallet_out',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='file_upload_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict_app.FileUploadHistory'),
        ),
    ]
