# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KppPalletData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OUT', '납품(직송포함)'), ('IN', '회수')], max_length=10, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('pallet', models.IntegerField(null=True)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanager_app.Code')),
            ],
        ),
        migrations.CreateModel(
            name='PalletCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palletcode', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kpppalletdata',
            name='palletcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanager_app.PalletCode'),
        ),
    ]
